### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by crumdev** [crumdev/fewd_project#2]
- [x] Create mobile first design
- [x] Responds to mobile
- [x] Responds to tablet
- [x] Responds to Desktop
- [x] Integrate a minimum of one FEWD framework (JQuery, AJAX, Angular, etc...)
- [x] Include useful comments
- [x] Hosted in it's own github repository
- [x] include a readme.md file
- [x] Readme Must have brief description of purpose
- [x] Readme Must include instructions for viewing the website
